name = "status-monitor"
type = "javascript"
account_id = "7dcad7e5c925385adde3ce2a3f5bb271"
workers_dev = true
compatibility_date = "2025-06-15"


[assets]
directory = "./dist"





[triggers]
crons = ["*/5 * * * *"]  # 每5分钟执行一次监控
