name = "status-monitor"
type = "javascript"
account_id = "7dcad7e5c925385adde3ce2a3f5bb271"
workers_dev = true
compatibility_date = "2025-06-15"
main = "src/index.ts"


[assets]
directory = "./dist"




kv_namespaces = [
  { binding = "uptime", id = "c2e444664f7c417b9a0f0eb65b77ee0c" }
]

[triggers]
crons = ["*/3 * * * *"]  # 每5分钟执行一次监控
